language: java
sudo: false
dist: precise

services:
  - postgresql

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

install:
  # Compile sources with Java 1.8
  - jdk_switcher use oraclejdk8
  - chmod -R 777 ./travis/install.sh
  - ./travis/install.sh
  # Switch back to the original JDK to run the tests
  - jdk_switcher use ${TRAVIS_JDK_VERSION}

before_script:
  - psql -c 'create database postgis_test;' -U postgres
  - psql -d "postgis_test" -U postgres -c "create extension postgis"